apiVersion: v1
kind: Secret
metadata:
  name: location-service-secret
type: Opaque
data:
  REDIS_PASSWORD: d2VicHJvamVjdDEyMw== # Base64-encoded "webproject123"
  AWS_REGION: dXMtZWFzdC0x # Base64-encoded "us-east-1"
  AWS_ACCESS_KEY_ID: QUtJQVJTVTdLUEZTRk1VTkpTVEE= # Base64-encoded "AKIARSU7KPFSFMUNJSTA"
  AWS_SECRET_ACCESS_KEY: d3MxTGYrRHAvcWNyeWtrbXVDZ2R3MEgvb2U5Q2tMaVdHRkRwaGNZaA== # Base64-encoded value
  AWS_PLACE_INDEX: UGxhY2UtSW5kZXgtMQ== # Base64-encoded "Place-Index-1"
  AWS_ROUTE_CALCULATOR: Um91dGUtQ2FsY3VsYXRvci0x # Base64-encoded "Route-Calculator-1"
