apiVersion: v1
kind: Secret
metadata:
  name: location-service-secret
type: Opaque
data:
  AWS_REGION: dXMtZWFzdC0xCg==
  AWS_ACCESS_KEY_ID: QUtJQVlSSDVORkNNQ0JNRVVXT1YK
  AWS_SECRET_ACCESS_KEY: UEQ1aHIwY1JrSE5DYmZEYVZLWWxrL2FVT21ZSnZ1OXdVWEo4d0lLNAo=
  AWS_PLACE_INDEX: UGxhY2UtSW5kZXgtMQo=
  AWS_ROUTE_CALCULATOR: Um91dGUtQ2FsY3VsYXRvci0xCg==
  JWT_SECRET: bG9jYXRpb24tc2VydmljZS1qd3Qtc2VjcmV0LWtleS0xMjM0NTY=
