apiVersion: v1
kind: Secret
metadata:
  name: location-service-secret
type: Opaque
data:
  REDIS_PASSWORD: d2VicHJvamVjdDEyMw==
  AWS_REGION: dXMtZWFzdC0x
  AWS_ACCESS_KEY_ID: QUtJQVJTVTdLUEZTRk1VTkpTVEE=
  AWS_SECRET_ACCESS_KEY: d3MxTGYrRHAvcWNyeWtrbXVDZ2R3MEgvb2U5Q2tMaVdHRkRwaGNZaA==
  AWS_PLACE_INDEX: UGxhY2UtSW5kZXgtMQ==
  AWS_ROUTE_CALCULATOR: Um91dGUtQ2FsY3VsYXRvci0x
  JWT_SECRET: bG9jYXRpb24tc2VydmljZS1qd3Qtc2VjcmV0LWtleS0xMjM0NTY=

